# Generated by Django 5.2.5 on 2025-08-25 04:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('movie', 'Фильм'), ('book', 'Книга'), ('other', 'Другое')], default='other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('normalized_text', models.CharField(editable=False, max_length=500, unique=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.source')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('value', models.SmallIntegerField(choices=[(1, 'like'), (-1, 'dislike')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quotes.quote')),
            ],
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['source', 'is_active'], name='quotes_quot_source__b75873_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['-likes', '-views'], name='quotes_quot_likes_ed2c9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('normalized_text',), name='uq_quote_normalized_text'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['quote', 'session_key'], name='quotes_vote_quote_i_1a817a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('quote', 'session_key')},
        ),
    ]
