# Generated by Django 5.2.5 on 2025-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_source_author_alter_quote_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='kind',
            field=models.CharField(choices=[('movie', 'Фильм'), ('book', 'Книга')], default='movie', max_length=20),
        ),
    ]
